src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEmbauche = null;

    #[ORM\ManyToOne(inversedBy: 'employe')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $entreprise = null;

    #[ORM\Column(length: 100)]
    private ?string $ville = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): static
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function __toString(){
        return $this->prenom." ".$this->nom;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function getAge(){
        $now = new \DateTime();
        $interval = date_diff($this->dateNaissance,$now);
        return $interval->format("%Y");
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])

            ->add('prenom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])

            ->add('dateNaissance', DateType::class, [
                'widget' =>'single_text',
                'attr' => ['class' => 'form-control']
            ])

            ->add('dateEmbauche', DateType::class, [
                'widget' =>'single_text',
                'attr' => ['class' => 'form-control']
            ])

            ->add('ville', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])

            ->add('entreprise', EntityType::class, [
                'class' => Entreprise::class,
                'choice_label' => 'raisonSociale',
                'attr' => ['class' => 'form-control']
            ])

            ->add('submit',SubmitType::class, [
                'attr' => ['class' => 'btn btn-success']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployeController extends AbstractController
{
    #[Route('/employe', name: 'app_employe')]
    public function index(ManagerRegistry $doctrine): Response{
        $employes = $doctrine->getRepository(Employe::class)->findBy([],["nom"=>"ASC"]);
        return $this->render('employe/index.html.twig', [
                "employes" => $employes
        ]);
    }

    #[Route('/employe/add', name: 'add_employe')]
    #[Route('/employe/{id}/edit', name: 'edit_employe')]
    public function add(ManagerRegistry $doctrine, Employe $employe = null, Request $request): Response{   
        if(!$employe){
            $employe = new Employe();
        }
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){
            $employe = $form->getData();
            $entityManager = $doctrine->getManager();
            $entityManager->persist($employe);
            $entityManager->flush();

            return $this->redirectToRoute('app_employe');
        }

        // vue pour afficher formulaire d'ajout
        return $this->render('employe/add.html.twig', [
            'formAddEmploye' => $form->createView(),
            'edit'=> $employe->getId()
        ]);
    }
    
    #[Route('/employe/{id}/delete', name: 'delete_employe')]
    public function delete(ManagerRegistry $doctrine, Employe $employe): Response{   
        $entityManager = $doctrine->getManager();
        $entityManager->remove($employe);
        $entityManager->flush();
        return $this->redirectToRoute('app_employe');
    }

    #[Route('/employe/{id}', name: 'show_employe')]
    public function show(Employe $employe): Response{   
        return $this->render('employe/show.html.twig', [
                "employe" => $employe
        ]);
    }
    
}

templates/employe/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter employe{% endblock %}

{% block body %}
    {% if edit %}
    <h1>Editer nom d'employé</h1>
    {% else %}
    <h1>Ajouter une employé</h1>
    {% endif %}
    {{ form_start(formAddEmploye) }}
        <div class="nomPrenom">
            {{form_row(formAddEmploye.prenom) }}
            {{form_row(formAddEmploye.nom) }}
        </div>
        <div>
            {{form_row(formAddEmploye.dateNaissance) }}
            {{form_row(formAddEmploye.dateEmbauche) }}
            {{form_row(formAddEmploye.ville) }}
            {{form_row(formAddEmploye.entreprise) }}
            {{form_row(formAddEmploye.submit) }}
        </div>

    {{ form_end(formAddEmploye) }}

{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}
    <h1>Liste des employés</h1>

    <a class="btn btn-primary" href="{{ path('add_employe')}}">Ajouter employe</a><br>

    {% for employe in employes %}
        <a href="{{ path('show_employe',{'id': employe.id}) }}">{{employe}}</a>
        <a class="btn btn-warning" href="{{ path('edit_employe',{'id': employe.id}) }}">Edit</a>
        <a class="btn btn-danger" href="{{ path('delete_employe',{'id': employe.id}) }}">Delete</a><br>

        {% endfor %}
{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details d'un employé!{% endblock %}

{% block body %}
    <h1>{{employe}}</h1>
    <p>
        Ville: {{ employe.ville }}<br>
        Entreprise: <a href="{{ path('show_entreprise',{'id': employe.entreprise.id}) }}">{{ employe.entreprise }}</a><br>
        Date embauche: {{ employe.dateEmbauche | date('d-m-Y') }}<br>
        Date naissance: {{ employe.age | date('d-m-Y') }} ({{employe.age}}) ans <br>
    </p>
{% endblock %}